### ISSUE TITLE
Wrong arXiv link for some papers in papers page

### ISSUE THREAD

**Issue by AllanChain** [netket/netket.org#8]
I was browsing https://www.netket.org/papers/ and found some paper has wrong arXiv link. For example, the arXiv link to _[Neural Projected Quantum Dynamics: a systematic study](https://www.netket.org/papers/gravina-pvqd-systematic/)_ should be [2410.10720](https://arxiv.org/abs/2410.10720) instead of [2410.1072](https://arxiv.org/abs/2410.1072):

![image](https://github.com/user-attachments/assets/be0ad20e-23ff-4b12-92e9-ffd0fc734baa)

Another example is _[Empirical sample complexity of neural network mixed state reconstruction](https://www.netket.org/papers/zhao-sample-complexity-ndm/)_, it should be [2307.01840](https://arxiv.org/abs/2307.01840) instead of [2307.0184](https://arxiv.org/abs/2307.0184).

Looks like the final `0` is somehow lost.

**Comment by PhilipVinc** [comment]
Thank you @AllanChain !
Indeed, the arxiv references where treated like numbers and therefore leading and trailing 0s where stripped.
I think the last commit should have solved it...
